display "" {

	background {
		color #000
	}
	
	globals {
		$level = 0
	}

	display {
		font "bubble-bobble"

		on "KEYPRESSED:+" {
			$level= $level + 1
			log("$level",$level)
		}

		layout {

			align center
			size 4

			$strings = [
				"THIS",
				"IS",
				"SPARTA"
			]

			def anim "fade" {
				path { 
					prop("text", $strings)
					loop()
				}
				speed 5
			}

			// text "BOBBLE BUBBLE" at:298,104 anim:"fade" traits:[$fadeout]
			text "BUBBLE BOBBLE" at:298,104 anim:"fade"

			def anim "toRight" {
				path {
					at(55,28)
					dir(right)
					line(1,55,28,520,28)
					dir(left)
					line(-1,55,28,520,28)
					loop()
				}
				speed 50
			}
			def anim "toLeft" {
				path {
					at(520,28)
					dir(left)
					line(-1,55,28,520,28)
					dir(right)
					line(1,55,28,520,28)
					loop()
				}
				speed 60
			}

			sprite "zen-chan" at:0,0 dir:right anim:"toRight"
			sprite "zen-chan" at:0,0 dir:left anim:"toLeft"

			// $level=1
			image "level-tiles:levels-S-${level}" at:48,60 range:32,0
			image "level-tiles:levels-L-${level}" at:48,60 range:0,13
			image "level-tiles:levels-L-${level}" at:528,60 range:0,13
			image "level-tiles:levels-S-${level}" at:48,460 range:32,0

			$top = $clientHeight - 110
			$width = $clientWidth - 50

			$pos= $clientWidth / 2 - $width / 2
			rect at:$pos,$top width:$width height:20 pad:5,5 fill:#FFFFFF50

			size 1
			color white
			align center
			valign center
			text "(${mouseX},${mouseY}) ${clientWidth}x${clientHeight}" at:10,$top width:$width height:20			
		}
	}

	entities {
		settings {
			show_entities_count = true
		}
	}


}